# Generated by Django 4.0 on 2022-03-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
